name: Doodle Backend CD
on:
  push:
    branches:
      - "master"
     
jobs:
  server-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/demo
            sudo git pull
            sudo docker-compose down
            sudo docker-compose up --build -d